# -*- coding: utf-8 -*-
"""IVP WEEK-2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIrLqNbBlMkLJQ6gPQhIXHH2FqDAyruv
"""

import cv2

img = cv2.imread("wallpaper.jpg", 0)

if img is None:
    print("Image not found!")
else:
    print("Image loaded successfully.")

from google.colab import files

uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("wallpaper.jpg", 0)

if img is None:
    print("Error: Image not found.")
else:
    threshold = np.mean(img)
    print("Mean Threshold =", threshold)

    binary = np.where(img >= threshold, 255, 0).astype(np.uint8)

    plt.figure(figsize=(10,5))

    plt.subplot(1,2,1)
    plt.imshow(img, cmap='gray')
    plt.title("Grayscale")
    plt.axis('off')

    plt.subplot(1,2,2)
    plt.imshow(binary, cmap='gray')
    plt.title("Binary")
    plt.axis('off')

    plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
img = cv2.imread("wallpaper.jpg")

if img is None:
    print("Image not found!")
else:
    # Convert BGR to RGB
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Split channels
    R = img_rgb[:, :, 0]
    G = img_rgb[:, :, 1]
    B = img_rgb[:, :, 2]

    # Mean of three channels
    gray = ((R.astype(float) + G.astype(float) + B.astype(float)) / 3).astype(np.uint8)

    plt.figure(figsize=(10,5))

    plt.subplot(1,2,1)
    plt.imshow(img_rgb)
    plt.title("Original RGB")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(gray, cmap="gray")
    plt.title("Grayscale (Average)")
    plt.axis("off")

    plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)

if img is None:
    print("Error loading image!")
else:
    # Convert BGR to RGB
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Separate channels
    R = img[:,:,0]
    G = img[:,:,1]
    B = img[:,:,2]

    # Mean average grayscale
    gray = ((R.astype(float) + G.astype(float) + B.astype(float))/3).astype(np.uint8)

    plt.figure(figsize=(10,5))

    plt.subplot(1,2,1)
    plt.imshow(img)
    plt.title("Original RGB Image")
    plt.axis('off')

    plt.subplot(1,2,2)
    plt.imshow(gray, cmap='gray')
    plt.title("Grayscale Image")
    plt.axis('off')

    plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)

if img is None:
    print("Error loading image!")
else:
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    wr = float(input("Enter weight for Red (0-1): "))
    wg = float(input("Enter weight for Green (0-1): "))
    wb = float(input("Enter weight for Blue (0-1): "))

    if (0 <= wr <= 1 and 0 <= wg <= 1 and 0 <= wb <= 1 and abs((wr + wg + wb) - 1) < 1e-6):

        R = img[:,:,0].astype(float)
        G = img[:,:,1].astype(float)
        B = img[:,:,2].astype(float)

        gray = (wr*R + wg*G + wb*B).astype(np.uint8)

        plt.figure(figsize=(10,5))

        plt.subplot(1,2,1)
        plt.imshow(img)
        plt.title("Original RGB Image")
        plt.axis('off')

        plt.subplot(1,2,2)
        plt.imshow(gray, cmap='gray')
        plt.title("Weighted Grayscale Image")
        plt.axis('off')

        plt.show()

    else:
        print("Invalid weights!")
        print("Each weight must be between 0 and 1.")
        print("The sum of all three weights must be exactly 1.")